# Generated by Django 4.1.7 on 2023-04-01 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('operation_name', models.CharField(choices=[('crop', 'Crop'), ('trim', 'Trim'), ('vflip', 'Vertical Flip'), ('hflip', 'Horizontal Flip'), ('resize', 'Resize')], max_length=32)),
                ('arguments', models.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.operationgroup')),
            ],
        ),
    ]
