# Generated by Django 4.1.7 on 2023-04-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_operationgroup_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='media.operationgroup'),
        ),
    ]
