# Generated by Django 4.1.7 on 2023-04-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='arguments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
