# Generated by Django 4.1.7 on 2023-04-01 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_operation_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quality_level',
            field=models.IntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51)]),
        ),
    ]
