# Generated by Django 4.1.7 on 2023-04-02 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_video_quality_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='quality_level',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(51)]),
        ),
    ]
